### ISSUE TITLE
Nested menu items

### ISSUE THREAD

**Issue by chasevida** [i-lateral/silverstripe-custommenus#4]
Hi there, I'm wondering if this module has the ability to nest menu items? When I've tried it I haven't seen something like this but maybe I just don't know how to implement it?

Thanks.

**Comment by mlewis-everley** [comment]
At the moment I have been emulating the current silverstripe standard menu (using loop children in the templates). 

Nested menu items would be an interesting idea, but probably would need to be an option on the menu item (as some users would probably prefer to carry on using the current process)?

I think doing this would involve a heavy re-write of this module, but any ideas, pull requests, etc are more than welcome :-)
