### ISSUE TITLE
CustomMenuHolder should use MenuTitle

### ISSUE THREAD

**Issue by henrypenny** [i-lateral/silverstripe-custommenus#7]
I think it would be more intuitive to use the Navigation label field ( `$MenuTitle` ) throughout the admin for this plugin:

`$fields->addFieldToTab('Root.Main', new TreeMultiselectField('Pages',_t('CustomMenus.FormPagesPages','Select pages'), 'SiteTree', "ID", "MenuTitle"));`

Or possibly make this configurable.

My client uses titles that are quite different to the navigation labels which causes a lot of confusion whilst building navs.

**Comment by mlewis-everley** [comment]
I hadn't even seen these issues, it should be less of an issue in the new version, but the best way to do this would be to remove the old field via an extension call and then re-add it using new config.
